### ISSUE TITLE
error when train

### ISSUE THREAD

**Issue by xy-git** [Ahmedest61/MRNetVLAD#2]
HI,thanks for your work!
when i train as the guide.
i run `    python main.py --mode=cluster --arch=vgg16-12 --pooling=netvlad --density_L=10 --num_clusters=64`
it's ok
and then i run `python main.py --mode=train --arch=vgg16-12 --pooling=netvlad --density_L=10 --num_clusters=64`
find the error
`Traceback (most recent call last):
  File "/home/Desktop/Link to projects/MultiRes-NetVLAD-main/main.py", line 594, in <module>
    raise ValueError('pca_layer can be used only during Testing')
ValueError: pca_layer can be used only during Testing
`
can u help me? thanks o lot

**Comment by Ahmedest61** [comment]
Hi, can you check that 'appendPcaLayer' value is set to be 'False'?

**Comment by Ahmedest61** [comment]
Hi, Thank you for pointing this out. I have removed the bug. Can you rerun it?

**Comment by xy-git** [comment]
Yes,it works now.
But when i try to train it on 4GPU
after 
` python main.py --mode=cluster --arch=vgg16-12 --pooling=netvlad --density_L=10 --num_clusters=64`
I run
` python main.py --mode=train --arch=vgg16-12 --pooling=netvlad --density_L=10 --num_clusters=64 --nGPU 4`
and change the cacheBatchSize as 24,48 or other number(default=12),it all failed
`RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`
while my GPU usd is only 15%,why?
i think maybe 1451(num of pic) can't divisible by 2?
can u help me ? thanks

**Comment by xy-git** [comment]
I  try to train on only 1 GPU, and don't change any parameter.
first time, it run 
` Building Cache 0/8
  0%|                                                                                  | 0/1451 `
and finished
then it run
`Allocated: 74883072                                                                                             
Cached: 81788928
  0%|                                                                                   | 0/229 [00:00<?, ?it/s]
******MultiRes-NetVLAD Training==> l:[2, 3, 4, 5, 6, 7, 8, 9, 10]*****`
and error
`Traceback (most recent call last):                                                                              
  File "main.py", line 684, in <module>
    train(epoch)
  File "main.py", line 199, in train
    loss.backward()
  File "/root/anaconda3/envs/patch/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/anaconda3/envs/patch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 174.00 MiB (GPU 0; 15.90 GiB total capacity; 14.85 GiB already allocated; 45.12 MiB free; 14.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
I try to change cacheBatchSize to 6, it still out of memory.
can u tell me what is the memory of your graphics card?
can u help me to fix it?
thanks a lot!
